services:
  http_server:
    build: ./http_server
    container_name: http_server
    network_mode: "host"
    restart: always

  ftp_server:
    build: ./ftp_server
    container_name: ftp_server
    ports:
      - "21:21"
      - "40000-40100:40000-40100" # Passive mode ports
    restart: always

  telnet_server:
    build: ./telnet_server
    container_name: telnet_server
    ports:
      - "23:23"
    restart: always
