services:
  http:
    image: nginx
    container_name: http
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.101
    ports:
      - "80:80/tcp"

networks:
  macvlan_net:
    external: true
