services:
  dns_server:
    image: ubuntu/bind9
    container_name: dns
    restart: always
    networks:
      macvlan_net:
        ipv4_address: ${DNS_SERVER_IP}
    environment:
      - BIND9_USER=root
      - DNS_SERVER_IP=${DNS_SERVER_IP}
      - WEB_SERVER_IP=${WEB_SERVER_IP}
      - IMAGE_SERVER_IP=${IMAGE_SERVER_IP}
    volumes:
      - ./dns/start-dns.sh:/start-dns.sh
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/db.template.local:/etc/bind/zones/db.template.local
      - ./dns/config:/etc/bind
    entrypoint: ["bash", "/start-dns.sh"]
    ports:
      - "53:53/udp"
      - "53:53/tcp"
  
  web_server:
    image: nginx
    container_name: http
    restart: always
    networks:
      macvlan_net:
        ipv4_address: ${WEB_SERVER_IP}
    volumes:
      - ./web_server:/usr/share/nginx/html:ro
    dns:
      - ${DNS_SERVER_IP}
    ports:
      - "80:80/tcp"
  
  image_server:
    build: ./image_server
    container_name: image 
    restart: always
    networks:
      macvlan_net:
        ipv4_address: ${IMAGE_SERVER_IP}
    dns:
      - ${DNS_SERVER_IP}
    ports:
      - "80:80/tcp"

networks:
  macvlan_net:
    external: true
