services:
  dns:
    image: ubuntu/bind9
    container_name: dns
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.100
    environment:
      - BIND9_USER=root
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./log:/var/log/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
  
  http:
    image: nginx
    container_name: http
    restart: always
    networks:
      macvlan_net:
        ipv4_address: 192.168.0.101
    ports:
      - "80:80/tcp"

networks:
  macvlan_net:
    external: true
